import { parseArgs } from 'node:util' // import command line argument parsing library
// these comments are not generated by chatgpt, you are welcome. 
import { PrismaClient } from '@prisma/client'
import { seedDev } from './seed.dev.js'
import { seedTest } from './seed.test.js'
import { seedDemo } from './seed.demo.js'

const options = { // define the options your script supports
  environment: { type: 'string' },
}
  const prisma = new PrismaClient();

async function main() {
  const {
    values: { environment },
  } = parseArgs({ options }) // get options

  switch (environment) { // add a case for each environment you want to support.

    case 'dev':
      /** data for your development */
      await seedDev(prisma);
      break;
    case 'test': 
      await seedTest(prisma);
      break;
    case 'demo':
      await seedDemo(prisma);
      break;
    default:
      throw new error("Invalid environment. Use --environment=dev|test|demo");
  }
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })